=== pritam-git/VSOH/public/xml-schema/updateTranslation.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="update">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="serverip" maxOccurs="1" minOccurs="1" type="xs:string" />
				<xs:element name="apikey" maxOccurs="1" minOccurs="1" type="xs:string" />
				<xs:element name="short" maxOccurs="1" minOccurs="1" type="xs:string" />
				<xs:element name="translations" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="short" maxOccurs="1" minOccurs="1" type="xs:string" />
							<xs:element name="translation" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="text" maxOccurs="1" minOccurs="1" type="xs:string" />
									</xs:sequence>
									<xs:attribute name="lang" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== pritam-git/VSOH/data/xmlStandard/updateTranslation.xml
<?xml version="1.0" encoding="UTF-8"?>
<update
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.l8m.com/xml-schema/updateTranslation.xsd">
	
	<serverip></serverip>
	<apikey></apikey>
	<short></short>
	<translations>
		<short>HTTP/1.1 403 Forbidden</short>
		<translation lang="en">
			<text>HTTP/1.1 403 Forbidden</text>
		</translation>
		<translation lang="de">
			<text>HTTP/1.1 403 Forbidden</text>
		</translation>
	
	</translations>
	
</update>
